# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Website App Kubernetes Deployment config. (https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)
# This is to be extended by the dev/autopush/staging/prod overlay.
# The deployment contains Flask web server container , gRPC mixer container and ESP container that transcodes grpc to JSON.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-app{{ .Values.resourceSuffix }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.website.replicas.default }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- if eq .Values.website.flaskEnv "custom" }}
      # Custom DCs can be completely unavailable for the short
      # period of time while new deployments become ready.
      # In return, we don't need extra compute resources
      # just for new pods during deployment.
      maxSurge: 50%
      maxUnavailable: 100%
      {{ else }}
      # maximum number of Pods that can be created over the desired number of Pods
      # 25% of default pods (+1 in case default < 4)
      maxSurge: {{ div .Values.website.replicas.default 4 | add 1 }}
      # Maximum number of pods that can be unavailable during the update process
      # 25% of default pods (+1 in case default < 4)
      maxUnavailable: {{ div .Values.website.replicas.default 4 | add 1 }}
      {{- end }}
  selector:
    matchLabels:
      app: website-app
  template:
    metadata:
      labels:
        app: website-app
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
        - name: ai-config
          configMap:
            name: ai-config{{ .Values.resourceSuffix }}
        - name: ingress-config
          configMap:
            name: ingress-config{{ .Values.resourceSuffix }}
{{- if .Values.nl.enabled }}
        - name: model-config
          configMap:
            name: model-config{{ .Values.resourceSuffix }}
{{- end }}
      containers:
        - name: website
          image:  "gcr.io/{{ .Values.website.image.project }}/datacommons-website:{{ .Values.website.image.tag }}"
          imagePullPolicy: {{ .Values.website.image.pullPolicy }}
          args: []
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 1
            periodSeconds: 10
          resources:
            limits:
              memory: "3G"
            requests:
              memory: "3G"
          volumeMounts:
            - name: ai-config
              mountPath: /datacommons/ai
            - name: ingress-config
              mountPath: /datacommons/ingress
          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: website-configmap{{ .Values.resourceSuffix }}
                  key: flaskEnv
            - name: WEBSITE_HASH
              valueFrom:
                configMapKeyRef:
                  name: githash-configmap{{ .Values.resourceSuffix }}
                  key: website_hash.txt
            - name: BIG_QUERY
              valueFrom:
                configMapKeyRef:
                  name: website-configmap{{ .Values.resourceSuffix }}
                  key: bigquery.version
            - name: ENABLE_MODEL
              valueFrom:
                configMapKeyRef:
                  name: website-configmap{{ .Values.resourceSuffix }}
                  key: enableModel
            - name: INGRESS_CONFIG_PATH
              value: /datacommons/ingress/rules
            # A dummy config used to bounce the server without any docker image
            # or data config change.
            - name: BOUNCE
              value: "dummy"
{{- if .Values.nl.enabled }}
        - name: nl
          image: gcr.io/datcom-ci/datacommons-nl:{{ .Values.website.image.tag }}
          resources:
            limits:
              memory: "2G"
            requests:
              memory: "2G"
          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: website-configmap{{ .Values.resourceSuffix }}
                  key: flaskEnv
          volumeMounts:
            - name: model-config
              mountPath: /datacommons/model
          startupProbe:
            httpGet:
              path: /healthz
              port: 6060
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 6060
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6060
          ports:
            - containerPort: 6060
{{- end }}